spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/jobs_backend}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1

logging:
  level:
    org.springframework.security: INFO
    org.flywaydb: INFO
