spring:
  datasource:
    url: ${DB_URL:jdbc:sqlite:db/getjobs.db}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  flyway:
    locations: classpath:db/sqlite
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: INFO
    org.flywaydb: INFO
